import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Share2, Download, Link2, Twitter, Linkedin, MessageCircle, Crop, ArrowUp } from 'lucide-react';
import { useDispatch } from 'react-redux';
import { sendMessage } from '../store/chatSlice';
import toast from 'react-hot-toast';

export default function ChatImage({ src, alt, conversationId }) {
  const [showShareMenu, setShowShareMenu] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showAspectRatioMenu, setShowAspectRatioMenu] = useState(false);
  const [editPrompt, setEditPrompt] = useState('');
  
  const dispatch = useDispatch();
  const shareRef = useRef(null);
  const aspectRef = useRef(null);

  // Close menus on outside click
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (shareRef.current && !shareRef.current.contains(event.target)) {
        setShowShareMenu(false);
      }
      if (aspectRef.current && !aspectRef.current.contains(event.target)) {
        setShowAspectRatioMenu(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleCopyLink = () => {
    navigator.clipboard.writeText(src);
    toast.success('Image link copied!');
    setShowShareMenu(false);
  };

  const handleDownload = async () => {
    try {
      const response = await fetch(src);
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `closer-ai-image-${Date.now()}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      // Wait before revoking to prevent .crdownload issue
      setTimeout(() => URL.revokeObjectURL(url), 2000);
      toast.success('Image downloaded!');
      setShowShareMenu(false);
    } catch (e) {
      console.error(e);
      window.open(src, '_blank');
      toast.error('Direct download failed. Opened in new tab.');
    }
  };

  const handleSocialShare = (platform) => {
    let url = '';
    const text = encodeURIComponent('Check out this image generated by Companion AI!');
    const encodedUrl = encodeURIComponent(src);

    switch (platform) {
      case 'x':
        url = `https://twitter.com/intent/tweet?text=${text}&url=${encodedUrl}`;
        break;
      case 'linkedin':
        url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}`;
        break;
      case 'reddit':
        url = `https://reddit.com/submit?url=${encodedUrl}&title=${text}`;
        break;
      case 'whatsapp':
        url = `https://api.whatsapp.com/send?text=${text} ${encodedUrl}`;
        break;
      default:
        break;
    }
    if (url) window.open(url, '_blank');
    setShowShareMenu(false);
  };

  const handleRegenerate = (promptText) => {
    if (!promptText.trim()) return;
    
    // Send a message to regenerate the image
    dispatch(sendMessage({
      conversationId: conversationId,
      message: `${promptText}\n[Context: Apply this to the previous image: ${src}]`,
    }));
    
    setShowEditModal(false);
    setEditPrompt('');
    setShowAspectRatioMenu(false);
  };

  const ASPECT_RATIOS = [
    { label: 'Square', ratio: '1:1' },
    { label: 'Portrait', ratio: '3:4' },
    { label: 'Story', ratio: '9:16' },
    { label: 'Landscape', ratio: '4:3' },
    { label: 'Widescreen', ratio: '16:9' }
  ];

  return (
    <>
      <div className="relative group block my-4 rounded-xl overflow-hidden shadow-2xl border border-white/10 bg-[#1e1e1e] w-fit max-w-full cursor-pointer" onClick={(e) => {
        // Prevent opening edit if clicking share button
        if (!e.target.closest('.share-btn-container')) {
          setShowEditModal(true);
        }
      }}>
        <img 
          src={src} 
          alt={alt || "Generated Output"} 
          className="rounded-xl w-auto max-h-[500px] object-contain block mx-auto transition-transform duration-300 group-hover:scale-[1.02]" 
          loading="lazy" 
        />
        
        {/* Hover Overlay */}
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end justify-between p-4 pointer-events-none">
          <button 
            className="px-3 py-1.5 bg-black/60 hover:bg-black/80 backdrop-blur-md text-white text-xs font-semibold rounded-full border border-white/20 transition pointer-events-auto"
            onClick={(e) => { e.stopPropagation(); setShowEditModal(true); }}
          >
            Edit
          </button>

          <div className="relative share-btn-container pointer-events-auto" ref={shareRef}>
            <button 
              className="p-2 bg-black/60 hover:bg-black/80 backdrop-blur-md text-white rounded-full border border-white/20 transition"
              onClick={(e) => { e.stopPropagation(); setShowShareMenu(!showShareMenu); }}
            >
              <Share2 className="w-4 h-4" />
            </button>

            <AnimatePresence>
              {showShareMenu && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9, y: 10 }}
                  animate={{ opacity: 1, scale: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.9, y: 10 }}
                  className="absolute bottom-full right-0 mb-3 w-max bg-panel border border-border/60 rounded-2xl shadow-2xl p-3 flex gap-3 z-50 backdrop-blur-xl"
                  onClick={(e) => e.stopPropagation()}
                >
                  <button onClick={handleCopyLink} className="flex flex-col items-center gap-1 group" title="Copy link">
                    <div className="w-10 h-10 rounded-full bg-surface group-hover:bg-accent flex items-center justify-center transition-colors">
                      <Link2 className="w-4 h-4 text-text group-hover:text-white" />
                    </div>
                    <span className="text-[10px] text-muted">Copy link</span>
                  </button>
                  <button onClick={() => handleSocialShare('x')} className="flex flex-col items-center gap-1 group" title="Share on X">
                    <div className="w-10 h-10 rounded-full bg-surface group-hover:bg-blue-500 flex items-center justify-center transition-colors">
                      <Twitter className="w-4 h-4 text-text group-hover:text-white" />
                    </div>
                    <span className="text-[10px] text-muted">X</span>
                  </button>
                  <button onClick={() => handleSocialShare('linkedin')} className="flex flex-col items-center gap-1 group" title="Share on LinkedIn">
                    <div className="w-10 h-10 rounded-full bg-surface group-hover:bg-blue-700 flex items-center justify-center transition-colors">
                      <Linkedin className="w-4 h-4 text-text group-hover:text-white" />
                    </div>
                    <span className="text-[10px] text-muted">LinkedIn</span>
                  </button>
                  <button onClick={() => handleSocialShare('reddit')} className="flex flex-col items-center gap-1 group" title="Share on Reddit">
                    <div className="w-10 h-10 rounded-full bg-surface group-hover:bg-orange-500 flex items-center justify-center transition-colors">
                      <MessageCircle className="w-4 h-4 text-text group-hover:text-white" />
                    </div>
                    <span className="text-[10px] text-muted">Reddit</span>
                  </button>
                  <button onClick={() => handleSocialShare('whatsapp')} className="flex flex-col items-center gap-1 group" title="Share on WhatsApp">
                    <div className="w-10 h-10 rounded-full bg-surface group-hover:bg-green-500 flex items-center justify-center transition-colors">
                      <MessageCircle className="w-4 h-4 text-text group-hover:text-white" />
                    </div>
                    <span className="text-[10px] text-muted">WhatsApp</span>
                  </button>
                  <button onClick={handleDownload} className="flex flex-col items-center gap-1 group" title="Download">
                    <div className="w-10 h-10 rounded-full bg-surface group-hover:bg-emerald-500 flex items-center justify-center transition-colors">
                      <Download className="w-4 h-4 text-text group-hover:text-white" />
                    </div>
                    <span className="text-[10px] text-muted">Download</span>
                  </button>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </div>

      {/* Fullscreen Editor Modal */}
      <AnimatePresence>
        {showEditModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] bg-black/95 flex flex-col"
          >
            {/* Top Bar */}
            <div className="flex items-center justify-between p-4 bg-transparent">
              <div className="flex items-center gap-4">
                <button 
                  onClick={() => setShowEditModal(false)}
                  className="p-2 hover:bg-white/10 rounded-full text-white transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
                <h3 className="text-white font-medium text-sm md:text-base truncate max-w-sm">
                  {alt && alt !== "Generated Output" ? alt : "Generated Image"}
                </h3>
              </div>

              <div className="flex items-center gap-3">
                <div className="relative" ref={aspectRef}>
                  <button 
                    onClick={() => setShowAspectRatioMenu(!showAspectRatioMenu)}
                    className="flex items-center gap-2 px-3 py-1.5 bg-white/10 hover:bg-white/20 text-white rounded-full text-sm font-medium transition-colors"
                  >
                    <Crop className="w-4 h-4" />
                    <span className="hidden sm:inline">Aspect ratio</span>
                  </button>
                  
                  <AnimatePresence>
                    {showAspectRatioMenu && (
                      <motion.div
                        initial={{ opacity: 0, y: 10, scale: 0.95 }}
                        animate={{ opacity: 1, y: 0, scale: 1 }}
                        exit={{ opacity: 0, y: 10, scale: 0.95 }}
                        className="absolute right-0 top-full mt-2 w-48 bg-[#1E1E1E] border border-white/10 rounded-2xl shadow-2xl p-2 z-50"
                      >
                        <div className="text-[11px] text-gray-400 px-3 py-2 uppercase font-semibold">
                          Generate this image with a different aspect ratio
                        </div>
                        {ASPECT_RATIOS.map(ar => (
                          <button
                            key={ar.ratio}
                            onClick={() => handleRegenerate(`Make the aspect ratio ${ar.ratio}`)}
                            className="w-full text-left px-3 py-2 text-sm text-gray-200 hover:bg-white/10 rounded-xl transition-colors flex items-center justify-between group"
                          >
                            <span>{ar.label}</span>
                            <span className="text-gray-500 group-hover:text-gray-300">{ar.ratio}</span>
                          </button>
                        ))}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
                
                <button 
                  onClick={() => setShowShareMenu(!showShareMenu)} 
                  className="px-4 py-1.5 bg-white hover:bg-gray-200 text-black rounded-full text-sm font-medium transition-colors"
                >
                  Share
                </button>
                <button onClick={handleDownload} className="p-2 hover:bg-white/10 text-white rounded-full transition-colors">
                  <Download className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Image Center */}
            <div className="flex-1 flex items-center justify-center p-6 min-h-0">
              <img 
                src={src} 
                alt={alt} 
                className="max-w-full max-h-full object-contain rounded-lg shadow-2xl" 
              />
            </div>

            {/* Bottom Bar */}
            <div className="p-6 pb-8 max-w-3xl w-full mx-auto">
              <div className="relative">
                <input
                  type="text"
                  placeholder="Describe edits"
                  value={editPrompt}
                  onChange={(e) => setEditPrompt(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      handleRegenerate(editPrompt);
                    }
                  }}
                  className="w-full bg-[#1E1E1E] text-white placeholder:text-gray-500 rounded-full pl-5 pr-12 py-3.5 outline-none border border-white/10 focus:border-white/30 transition-colors shadow-lg"
                />
                <button 
                  onClick={() => handleRegenerate(editPrompt)}
                  disabled={!editPrompt.trim()}
                  className="absolute right-2 top-1/2 -translate-y-1/2 w-8 h-8 flex items-center justify-center bg-white disabled:bg-white/20 text-black disabled:text-gray-500 rounded-full transition-colors"
                >
                  <ArrowUp className="w-4 h-4" />
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
